export interface PostCardType {
    id: number,
    date: string,
    title: string,
    meetingName: string,
    when: string,
    where: string,
    maximum: number,
    current: number,
    imageUrl: string,
    nickname: string,
    participationStatus: boolean,
}

export interface postDetailInfoType {
        groupId: number,
        memberId: number,
        nickname : string,
        image : string,
        title: string,
        name: string,
        content: string,
        food: string,
        date: string,
        time: string,
        maximum: number,
        current: number,
        storeName: string,
        storeAddress: string,
        latitude: string,
        longitude: string,
        createdDate: string,
        chatRoomId : number,
}